// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKb33DuHBRkzSQmgaq8J4c-3kDb-kz7O8',
    appId: '1:716487127525:web:0862df4c8e3526092c3f0c',
    messagingSenderId: '716487127525',
    projectId: 'flutter-dev-46255',
    authDomain: 'flutter-dev-46255.firebaseapp.com',
    storageBucket: 'flutter-dev-46255.appspot.com',
    measurementId: 'G-T7K8JBQRG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7kdh9ZB4eKblUCNV3eOyeylUsTUvZqRk',
    appId: '1:716487127525:android:9b1462a184cdab8f2c3f0c',
    messagingSenderId: '716487127525',
    projectId: 'flutter-dev-46255',
    storageBucket: 'flutter-dev-46255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXtQiOwkEIivyWeRwMPZHP1yKQd2KO38',
    appId: '1:716487127525:ios:ad9c3c6ea5f932a32c3f0c',
    messagingSenderId: '716487127525',
    projectId: 'flutter-dev-46255',
    storageBucket: 'flutter-dev-46255.appspot.com',
    iosBundleId: 'com.example.flutterDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASXtQiOwkEIivyWeRwMPZHP1yKQd2KO38',
    appId: '1:716487127525:ios:091f3d5759e87d132c3f0c',
    messagingSenderId: '716487127525',
    projectId: 'flutter-dev-46255',
    storageBucket: 'flutter-dev-46255.appspot.com',
    iosBundleId: 'com.example.flutterDev.RunnerTests',
  );
}
