// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfaIRbmCtDpyIHSARCjJSwMVLWRu0Gk4',
    appId: '1:782892165043:web:9a8dee179784af1fde0dc6',
    messagingSenderId: '782892165043',
    projectId: 'movilesflutter',
    authDomain: 'movilesflutter.firebaseapp.com',
    storageBucket: 'movilesflutter.appspot.com',
    measurementId: 'G-S62MY44ZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJ4S9vDbJNDK7iYtDC4LZcSsfug3eal8',
    appId: '1:782892165043:android:a74231bd0782325fde0dc6',
    messagingSenderId: '782892165043',
    projectId: 'movilesflutter',
    storageBucket: 'movilesflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNcCFJBQQxExzkOCuKAvizP8Tc5pv508',
    appId: '1:782892165043:ios:7cc2bfce0e28e4b0de0dc6',
    messagingSenderId: '782892165043',
    projectId: 'movilesflutter',
    storageBucket: 'movilesflutter.appspot.com',
    iosClientId: '782892165043-jfbb63g9apse5pk7nlhl85vh3hp7jqe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrNcCFJBQQxExzkOCuKAvizP8Tc5pv508',
    appId: '1:782892165043:ios:3c0cdee0cc2b1adbde0dc6',
    messagingSenderId: '782892165043',
    projectId: 'movilesflutter',
    storageBucket: 'movilesflutter.appspot.com',
    iosClientId: '782892165043-3bu7pe3ppgmn6njecb5pdg5n357u46i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev.RunnerTests',
  );
}
